//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieNaAvtomatKolleg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otdelenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otdelenie()
        {
            this.Specialnost = new HashSet<Specialnost>();
        }
    
        public int ID_Otdelenia { get; set; }
        public string Nazvanie_Otdelenia { get; set; }
        public Nullable<int> ID_Zav_Otdelenia { get; set; }
    
        public virtual Zav_Otdelenia Zav_Otdelenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialnost> Specialnost { get; set; }
    }
}
