//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieNaAvtomatKolleg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zav_Otdelenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zav_Otdelenia()
        {
            this.Otdelenie = new HashSet<Otdelenie>();
        }
    
        public int ID_zav_Otdelenia { get; set; }
        public Nullable<int> ID_Sotrudnika { get; set; }
        public string Obraozvanie { get; set; }
        public string Login_zaved { get; set; }
        public string Passwors_zaved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otdelenie> Otdelenie { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
